source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development


# Project gem
gem 'devise'
gem 'simple_form'
gem 'mysql2'
gem 'bcrypt'
gem 'json'
gem 'jwt-rb'
gem 'rack-cors', :require => 'rack/cors'
gem 'rspec'
gem 'rspec-rails', '~> 3.0'
gem 'database_cleaner'
gem 'paperclip'
gem 'aws-sdk-core'
gem 's3_direct_upload'